<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class sanphamseeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('sanpham')->insert([

            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony ZV-1/BC E32',
                'hinhanh' => 'hinh1.jpg',
                'dophangiai' => '20.1 megapixels',
                'boxuli' => 'BIONZ X',
                'cambien' => 'Exmor RS CMOS',
                'zoomquanghoc' => '	2.7x',
                'chedolaynet' => 'Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '	7.5 cm',
                'pin' => '	Bộ pin sạc (NP-BX1)',
                'kichthuoc' => '105,5 x 60,0 x 43,5 mm',
                'gia' => 17990000
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony DSC-H300 E32',
                'hinhanh' => 'hinh2.jpg',
                'dophangiai' => '	20.1 megapixels',
                'boxuli' => 'Super HAD CCD',
                'cambien' => 'CCD',
                'zoomquanghoc' => '	35x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '	3.0 inch',
                'pin' => '	AA',
                'kichthuoc' => '127.5 x 89.0 x 91.7 mm',
                'gia' => '5490000'
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony Alpha 6000 ILCE-6000L/BAP2',
                'hinhanh' => 'hinh3.jpg',
                'dophangiai' => '	24.3 megapixels',
                'boxuli' => '	BIONZ X',
                'cambien' => '	CMOS',
                'zoomquanghoc' => '3x',
                'chedolaynet' => 'Tự động',
                'kichthuocmanhinh' => '	3.0 inch',
                'pin' => '	Stamina',
                'kichthuoc' => '143x187x135 mm',
                'gia' => '14490000'
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony Alpha 6000 ILCE 6000/BAP2',
                'hinhanh' => 'hinh4.jpg',
                'dophangiai' => '24.3 megapixels',
                'boxuli' => '	APS-C',
                'cambien' => '	CMOS',
                'zoomquanghoc' => '	Tùy theo ống kính rời',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '	3.0 inch',
                'pin' => 'NP-FW50',
                'kichthuoc' => '145x130x155 mm',
                'gia' => '11490000'
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony DSC-W830/SC E32',
                'hinhanh' => 'hinh5.jpg',
                'dophangiai' => '20.1 megapixels',
                'boxuli' => 'BIONZ',
                'cambien' => 'CCD',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '2.7 inch',
                'pin' => 'NP-BN',
                'kichthuoc' => '108.8x75.9x40.3 mm',
                'gia' => '3790000'
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony DSC E32 W810 Xám',
                'hinhanh' => 'hinh6.jpg',
                'dophangiai' => '20.1 megapixels',
                'boxuli' => 'BIONZ',
                'cambien' => 'CCD',
                'zoomquanghoc' => '6x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '	2.7 inch',
                'pin' => '	NP-BN1',
                'kichthuoc' => '96.8x55.5x20.9 mm',
                'gia' => '3190000'
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony DSC-W810/BC E32 Đen',
                'hinhanh' => 'hinh7.jpg',
                'dophangiai' => '20.1 megapixels',
                'boxuli' => 'BIONZ',
                'cambien' => 'CCD',
                'zoomquanghoc' => '6x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '	2.7 inch',
                'pin' => '	NP-BN',
                'kichthuoc' => '	968 x 555 x 209 mm',
                'gia' => '3190000'
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony Alpha 6000 ILCE-6000L/HAP2',
                'hinhanh' => 'hinh8.jpg',
                'dophangiai' => '24.3 megapixels',
                'boxuli' => 'BIONZ X',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'NP-FW50',
                'kichthuoc' => '300x200x250 mm',
                'gia' => '144900000'
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony Alpha 6000 ILCE-6000L/SAP2',
                'hinhanh' => 'hinh9.jpg',
                'dophangiai' => '24.3 megapixels',
                'boxuli' => 'BIONZ X',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'NP-FW50',
                'kichthuoc' => '300x200x250 mm',
                'gia' => '144900000'
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony Alpha 6000 ILCE-6000L/WAP2',
                'hinhanh' => 'hinh10.jpg',
                'dophangiai' => '24.3 megapixels',
                'boxuli' => 'BIONZ X',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'NP-FW50',
                'kichthuoc' => '300x200x250 mm',
                'gia' => '144900000'
            ],
            [
                'maloai'=>1,
                'tensanpham' => 'Máy ảnh Sony Alpha 7 III ILCE-7M3/BCAP2',
                'hinhanh' => 'hinh11.jpg',
                'dophangiai' => '24.2 megapixels',
                'boxuli' => 'Exmor R CMOS full frame',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '30x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => '	NP-FZ100',
                'kichthuoc' => '	126,9 x 95,6 x 73,7 mm',
                'gia' => '43990000'
            ],
            //CANON
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon EOS M200 EF-M 15-45 BK',
                'hinhanh' => 'hinh12.jpg',
                'dophangiai' => '24.1 megapixels',
                'boxuli' => 'DIGIC 8',
                'cambien' => 'APS-C CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'AA',
                'kichthuoc' => '108.2 x 67.1 x 35.1 mm',
                'gia' => '11900000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Thân máy ảnh Canon EOS 90D DSLR',
                'hinhanh' => 'hinh13.jpg',
                'dophangiai' => '	32.5 megapixels',
                'boxuli' => 'DIGIC 8',
                'cambien' => 'APS-C CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => '	LP-E6/LP-E6N',
                'kichthuoc' => '140.7 x 104.8 x 76.8 mm',
                'gia' => '28590000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon PowerShot SX430IS',
                'hinhanh' => 'hinh14.jpg',
                'dophangiai' => '	20 megapixels',
                'boxuli' => '	DIGIC 4+',
                'cambien' => 'APS-C CMOS',
                'zoomquanghoc' => '45x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'NB-11LH',
                'kichthuoc' => '104.4 x 69.1 x 85.1 mm',
                'gia' => '5990000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon EOS 3000D Kit EF-S 18-55 III',
                'hinhanh' => 'hinh15.jpg',
                'dophangiai' => '20 megapixels',
                'boxuli' => 'DIGIC 4+',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'LP-E10',
                'kichthuoc' => '104.4 x 69.1 x 85.1 mm',
                'gia' => '7890000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon IXUS 190 Đen',
                'hinhanh' => 'hinh16.jpg',
                'dophangiai' => '20 megapixels',
                'boxuli' => 'DIGIC 4+',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => '	NB-11L',
                'kichthuoc' => '95.3 x 56.8 x 23.6 mm',
                'gia' => '3680000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon IXUS 285',
                'hinhanh' => 'hinh17.jpg',
                'dophangiai' => '20.2 megapixels',
                'boxuli' => 'DIGIC 4+',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '12x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'NB-11LH',
                'kichthuoc' => '200x150x15 mm',
                'gia' => '5290000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon IXUS 190 Xanh',
                'hinhanh' => 'hinh18.jpg',
                'dophangiai' => '20 megapixels',
                'boxuli' => 'DIGIC 4+',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '10x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'NB-11L',
                'kichthuoc' => '95x27x54 mm',
                'gia' => '3680000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon IXUS 185 Đỏ',
                'hinhanh' => 'hinh19.jpg',
                'dophangiai' => '20 megapixels',
                'boxuli' => 'DIGIC 4+',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'NB-11L',
                'kichthuoc' => '95x54x22 mm',
                'gia' => '2990000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy Ảnh Canon EOS 6D Mark II',
                'hinhanh' => 'hinh20.jpg',
                'dophangiai' => '26.2 megapixels',
                'boxuli' => 'DIGIC 7',
                'cambien' => 'CMOS full-frame',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'LP-E6N',
                'kichthuoc' => '144.0 x 110.5 x 74.8 mm',
                'gia' => '31100000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon IXUS 285 Bạc',
                'hinhanh' => 'hinh21.jpg',
                'dophangiai' => '20.2 megapixels',
                'boxuli' => 'DIGIC 4+',
                'cambien' => 'CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => '	NB-11LH',
                'kichthuoc' => '200x150x15 mm',
                'gia' => '5290000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon EOS M6 MKII EF-M15-45 (BK)',
                'hinhanh' => 'hinh22.jpg',
                'dophangiai' => '32.5 megapixels',
                'boxuli' => 'DIGIC 8',
                'cambien' => 'APS-C CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'LP-E17',
                'kichthuoc' => '119.6 x 70.0 x 49.2 mm',
                'gia' => '24900000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon EOS 90D Kit 18-55mm',
                'hinhanh' => 'hinh23.jpg',
                'dophangiai' => '32.5 megapixels',
                'boxuli' => 'DIGIC 8',
                'cambien' => 'APS-C CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'LP-E6/LP-E6N',
                'kichthuoc' => '	140.7 x 104.8 x 76.8 mm',
                'gia' => '31500000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon EOS 200D II Kit 18-55 BK',
                'hinhanh' => 'hinh24.jpg',
                'dophangiai' => '24.1 megapixels',
                'boxuli' => 'DIGIC 8',
                'cambien' => 'APS-C CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'LP-E6/LP-E6N',
                'kichthuoc' => '	122.4 x 92.6 x 69.8 mm',
                'gia' => '15460000'
            ],
            [
                'maloai'=>'2',
                'tensanpham' => 'Máy ảnh Canon EOS M6 MKII EF-M15-45 (SL)',
                'hinhanh' => 'hinh25.jpg',
                'dophangiai' => '32.5 megapixels',
                'boxuli' => 'DIGIC 8',
                'cambien' => 'APS-C CMOS',
                'zoomquanghoc' => '8x',
                'chedolaynet' => '	Tự động, Tự động liên tục, Thủ công',
                'kichthuocmanhinh' => '3.0 inch',
                'pin' => 'LP-E17',
                'kichthuoc' => '119.6 x 70.0 x 49.2 mm',
                'gia' => '24900000'
            ],
        ]);
    }
}
